services:
  postgres:
    image: postgres:15
    container_name: warranty_wallet_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: warranty
      POSTGRES_DB: Warrant_wallet_v02
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: